const SITE_BASE=import.meta.env.BASE_URL.replace(/\/$/,'');
const readRoute=()=>{const raw=location.pathname;const route=SITE_BASE&&raw.startsWith(SITE_BASE+'/')?raw.slice(SITE_BASE.length):raw===SITE_BASE?'/':raw;return route.replace(/\/+$/,'')||'/';};
import React, {useState, useEffect, useRef, createContext, useContext, lazy, Suspense} from 'react';
import * as Dialog from '@radix-ui/react-dialog';
import {ArrowUpRight, ArrowRight, ArrowLeft, MagnifyingGlass, X, List, PencilSimple, CaretLeft, CaretRight, Check, BookOpen, ArrowUp, SignOut, Copy, EnvelopeSimple, Phone, ChatCircle} from '@phosphor-icons/react';
import {motion, useReducedMotion} from 'motion/react';
import Markdown from 'react-markdown';
import {seed,nav} from './data';
import {OWNER_ENABLED,ownerRequest} from './storage';
const Editor=OWNER_ENABLED ? lazy(()=>import('./Editor')) : null;
const OwnerLogin=OWNER_ENABLED ? lazy(()=>import('./OwnerLogin')) : null;
const Router=createContext(null);
function Link({to,children,onClick,...props}){const router=useContext(Router);return <a href={SITE_BASE+to} {...props} onClick={e=>{onClick?.(e);if(!e.defaultPrevented&&!e.metaKey&&!e.ctrlKey&&!e.shiftKey&&e.button===0){e.preventDefault();router.go(to);}}}>{children}</a>;}
export const Arrow=({up=false,...props})=>up?<ArrowUpRight weight="light" size={20} aria-hidden {...props}/>:<ArrowRight weight="light" size={21} aria-hidden {...props}/>;
export function Modal({open,onOpenChange,title,description,children,className='',closeLabel='关闭'}){return <Dialog.Root open={open} onOpenChange={onOpenChange}><Dialog.Portal><Dialog.Overlay className="overlay"/><Dialog.Content className={`dialog ${className}`}><Dialog.Title className="dialog-title">{title}</Dialog.Title>{description?<Dialog.Description className="dialog-desc">{description}</Dialog.Description>:<Dialog.Description className="sr-only">{title}</Dialog.Description>}<Dialog.Close className="icon-button close-button" aria-label={closeLabel} title={closeLabel}><X size={23}/></Dialog.Close>{children}</Dialog.Content></Dialog.Portal></Dialog.Root>;}
function Reveal({children,className='',delay=0}){const reduce=useReducedMotion();return <motion.div className={className} initial={reduce?false:{opacity:0,transform:'translateY(12px)'}} whileInView={{opacity:1,transform:'translateY(0px)'}} viewport={{once:true,amount:.1}} transition={{duration:.5,delay,ease:[.23,1,.32,1]}}>{children}</motion.div>;}
function Socials({data,full=false}){return <div className={`socials ${full?'socials-full':''}`}>{data.socials.map(s=><a key={s.label} href={s.url} target="_blank" rel="noopener noreferrer">{full&&<span className="social-caption">{s.nickname}</span>}<span>{s.label}<Arrow up/></span>{full&&<small>在这里，看更多生活记录</small>}</a>)}</div>;}
function Header({path,data,search}){const [menu,setMenu]=useState(false);useEffect(()=>setMenu(false),[path]);return <header className="header"><Link to="/" className="brand" aria-label={`${data.profile.englishName}，返回首页`}><span>{data.profile.englishName}</span></Link><nav className="desktop-nav" aria-label="主导航">{nav.map(([p,l])=><Link key={p} to={p} aria-current={p==='/'?path==='/'?'page':undefined:path.startsWith(p)?'page':undefined}>{l}</Link>)}</nav><div className="header-tools"><button className="icon-button" onClick={search} aria-label="搜索网站"><MagnifyingGlass size={25} weight="light"/></button><button className="icon-button mobile-menu-button" aria-label="打开导航" onClick={()=>setMenu(true)}><List size={26}/></button></div><Modal open={menu} onOpenChange={setMenu} title="去哪里看看" className="menu-dialog"><nav aria-label="手机导航">{nav.map(([p,l],i)=><Link key={p} to={p} onClick={()=>setMenu(false)}><span className="eyebrow">0{i+1}</span>{l}<Arrow/></Link>)}</nav><Socials data={data}/></Modal></header>;}
function Footer({data,edit,owner,logout}){return <footer className="footer"><Socials data={data}/><Link className="footer-contact text-link" to="/about">联系我<Arrow up/></Link><div className="footer-meta"><span>© {new Date().getFullYear()} {data.profile.name}</span>{OWNER_ENABLED&&<><button className="owner-link icon-button" onClick={edit} aria-label={owner?"编辑内容":"站主登录"} title={owner?"编辑内容":"站主登录"}><PencilSimple size={15}/></button>{owner&&<button className="owner-link icon-button" aria-label="退出登录" title="退出登录" onClick={logout}><SignOut size={16}/></button>}</>}<button className="icon-button back-top" aria-label="回到顶部" onClick={()=>window.scrollTo({top:0,behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'})}><ArrowUp size={16}/></button></div></footer>;}
function Pathways(){return <section className="pathways" aria-label="探索三个方向">{[['/work','01 / 做过什么','项目与实践'],['/notes','02 / 如何思考','学习与思考'],['/life','03 / 日常的我','生活与兴趣']].map(([to,label,title])=><Link to={to} key={to} className="pathway"><span>{label}</span><div><h2>{title}</h2><Arrow/></div></Link>)}</section>;}
const journeys={notes:['02 / 学习与思考','从做过的事，到正在想的问题。','产品方法、界面设计与工程实践中的学习记录。','/notes','继续看看我的思考'],life:['03 / 生活与兴趣','合上笔记，去生活里看看。','球场、舞台、电影，以及和朋友一起的日常。','/life','看看生活里的我'],about:['04 / 关于我','如果有共同的话题，认识一下。','更多个人经历，也欢迎交流、约球或聊聊合作。','/about','认识我与联系'],work:['01 / 项目与实践','从认识彼此，到看看我的实践。','产品、数据与校园协作，记录一步步做过的事。','/work','看看我的项目与实践']};
function Journey({next}){const [eyebrow,title,desc,to,label]=journeys[next];return <nav className="page-journey" aria-label="继续探索"><div><p className="eyebrow">下一站 · {eyebrow}</p><h2>{title}</h2><p>{desc}</p></div><Link to={to} className="journey-link">{label}<Arrow/></Link></nav>;}
function Interests({data}){return <section className="interest-section" aria-labelledby="interest-heading"><div className="section-heading"><p className="eyebrow">OFF THE CLOCK</p><h2 id="interest-heading">离开屏幕以后</h2></div><p>喜欢打羽毛球、看电影，也喜欢和朋友玩桌游、剧本杀、麻将。游戏的话，我玩王者。</p><ul className="interest-tags">{(data.profile.interests||'').split('\n').filter(Boolean).map(x=><li key={x}>{x}</li>)}</ul></section>;}
function ContactSection({data}){const [message,setMessage]=useState('');const p=data.profile;async function copy(){try{await navigator.clipboard.writeText(p.wechat);setMessage('微信号已复制');}catch{setMessage('复制未成功，可以选中微信号手动复制');}}return <section className="contact-section" id="contact" aria-labelledby="contact-heading"><div className="section-heading"><p className="eyebrow">LET’S TALK</p><h2 id="contact-heading">从一句你好开始</h2><p>聊产品与技术、交流校园经历，或者约一场球。</p></div><div className="contact-grid">{p.wechat&&<div className="contact-card"><ChatCircle size={22} weight="light"/><span>微信</span><strong>{p.wechat}</strong><button className="text-link" onClick={copy}>复制微信号<Copy size={16}/></button></div>}{p.email&&<a className="contact-card" href={`mailto:${p.email}`} aria-label={`发送邮件到 ${p.email}`}><EnvelopeSimple size={22} weight="light"/><span>邮箱</span><strong>{p.email}</strong><span className="text-link">写封邮件<Arrow up/></span></a>}{p.phone&&<a className="contact-card" href={`tel:${p.phone}`} aria-label={`拨打电话 ${p.phone}`}><Phone size={22} weight="light"/><span>电话</span><strong>{p.phone}</strong><span className="text-link">电话联系<Arrow up/></span></a>}</div><p className="contact-status" role="status">{message}</p></section>;}
function Home({data,editing,edit}){const p=data.profile;return <><section className="hero" aria-labelledby="hero-title"><img className="hero-image" src={p.hero} alt="胡杨赫俊身穿蓝色西装，站在暖木色厅堂的栏杆旁" fetchPriority="high"/><div className="hero-inner"><Reveal><p className="eyebrow hero-eyebrow">PERSONAL STUDIO <span>/ {p.name}</span></p></Reveal><Reveal delay={.05}><h1 id="hero-title">{p.headline}<br/><em>{p.accent}</em></h1></Reveal><Reveal delay={.1}><p className="hero-intro">{p.intro}</p><div className="hero-actions"><Link className="button primary" to="/about">认识我<Arrow up/></Link><Link className="text-link" to="/work">看看我做的事<Arrow/></Link></div></Reveal>{editing&&<button className="edit-control edit-section" aria-label="编辑首页" onClick={()=>edit('profile')}><PencilSimple size={17} aria-hidden="true"/><span className="edit-tooltip" aria-hidden="true">编辑首页</span></button>}</div></section><Pathways/><section className="featured-section"><div className="featured-project"><h2 className="section-label">精选实践</h2><Link to={`/work/${data.work[0].id}`} className="story-link"><h3>{data.work[0].title}</h3><p>{data.work[0].summary}</p><span className="text-link">阅读全文<Arrow/></span></Link></div><div className="featured-life"><Link className="stage-image" to={`/work/${data.work[1].id}`} tabIndex={-1} aria-hidden><img src={data.work[1].image} alt="" loading="lazy"/></Link><Link to={`/work/${data.work[1].id}`} className="story-link"><h3>{data.work[1].title}</h3><p>{data.work[1].summary}</p><span className="text-link">阅读全文<Arrow/></span></Link></div></section></>;}
function PageHeading({eyebrow,title,description,children}){return <Reveal className="page-heading"><p className="eyebrow">{eyebrow}</p><h1>{title}</h1>{description&&<p className="page-description">{description}</p>}{children}</Reveal>;}
function Tabs({options,value,onChange}){return <div className="filters" aria-label="内容分类">{options.map(x=><button key={x} aria-pressed={value===x} onClick={()=>onChange(x)}>{x}</button>)}</div>;}
function Work({data,filter,setFilter}){const categories=[...new Set(data.work.map(w=>w.type))].sort((a,b)=>['产品与技术','数据与建模','组织与表达','内容与运营'].indexOf(a)-['产品与技术','数据与建模','组织与表达','内容与运营'].indexOf(b));const ordered=categories.flatMap(type=>data.work.filter(w=>w.type===type));const groups=categories.filter(x=>filter==='全部'||filter===x);const descriptions={'产品与技术':'把需求转化为可用的产品与界面。','数据与建模':'用数据、特征与模型练习分析问题。','组织与表达':'在活动、舞台与校园协作中连接彼此。','内容与运营':'面向具体受众，组织信息与传播内容。'};return <div className="page-wrap"><PageHeading eyebrow="01 / PROJECTS & PRACTICE" title="项目与实践" description="从 AI 产品到数据建模，从校园组织到内容运营。这里记录做过的事、我的角色，以及具体的协作与实践。"/><div className="collection-meta"><span>{data.work.length} 段实践</span><span>{categories.length} 个方向</span></div><Tabs options={['全部',...categories]} value={filter} onChange={setFilter}/>{groups.map(type=><section className="collection-group" key={type}><div className="collection-heading"><h2>{type}</h2><p>{descriptions[type]}</p></div><div className="work-list">{data.work.filter(w=>w.type===type).map(w=><Reveal key={w.id}><Link to={`/work/${w.id}`} className={`work-row ${w.image?'has-image':''}`}><span className="work-number">{String(ordered.indexOf(w)+1).padStart(2,'0')}</span><div><h3>{w.title}</h3><p>{w.summary}</p><span className="work-role">{w.role}</span></div>{w.image&&<img src={w.image} alt="校园活动主持"/>}<span className="round-arrow"><Arrow up/></span></Link></Reveal>)}</div></section>)}{!groups.length&&<p className="empty-state">这个分类还没有内容，可以切换到全部实践。</p>}<Journey next="notes"/></div>;}
function Notes({data,filter,setFilter}){const categories=[...new Set(data.notes.map(n=>n.category))];return <div className="page-wrap"><PageHeading eyebrow="02 / LEARNING & REFLECTIONS" title="学习与思考" description="把实践里的问题慢慢想清楚。这里是从个人知识库整理出的产品方法、设计观察与工程笔记。"/><div className="collection-meta"><span>{data.notes.length} 篇整理笔记</span><span>持续学习，持续更新</span></div><Tabs options={['全部',...categories]} value={filter} onChange={setFilter}/>{categories.filter(x=>filter==='全部'||filter===x).map(category=><section className="collection-group" key={category}><div className="collection-heading"><h2>{category}</h2><p>{category==='AI 与产品'?'先理解场景，再作产品取舍。':'让界面更清楚，让实践可以复用。'}</p></div><div className="notes-list">{data.notes.filter(n=>n.category===category).map(n=><Reveal key={n.id}><Link to={`/notes/${n.id}`} className="note-row"><span className="note-index">{String(data.notes.indexOf(n)+1).padStart(2,'0')}</span><div><h3>{n.title}</h3><p>{n.summary}</p></div><Arrow/></Link></Reveal>)}</div></section>)}{filter!=='全部'&&!categories.includes(filter)&&<p className="empty-state">暂时没有这一主题，试试其他分类。</p>}<Journey next="life"/></div>;}
function Article({entry,kind,data}){const [copied,setCopied]=useState(false);if(!entry)return <NotFound/>;return <div className="article-wrap"><Link className="text-link back-link" to={kind==='notes'?'/notes':'/work'}><ArrowLeft size={18}/>{kind==='notes'?'所有学习笔记':'所有项目与实践'}</Link><header className="article-header"><p className="eyebrow">{entry.category||entry.type}</p><h1>{entry.title}</h1><p>{entry.summary}</p><div className="article-byline"><span>{data.profile.name} / {data.profile.englishName}</span><button className="text-link" onClick={async()=>{try{await navigator.clipboard.writeText(location.href);setCopied(true);}catch{setCopied(false);}}}>{copied?<><Check/>已复制链接</>:<>复制链接<Arrow up/></>}</button></div></header>{entry.image&&<img className="article-image" src={entry.image} alt="校园活动中手持麦克风和讲稿"/>}<div className="article-layout"><article className="prose"><Markdown>{entry.body}</Markdown>{entry.source&&<p className="article-source">{entry.source}</p>}</article><aside className="article-aside"><p className="eyebrow">阅读这篇{kind==='notes'?'笔记':'实践'}</p><p>慢慢看，<br/>也欢迎交流。</p><Socials data={data}/></aside></div><Journey next={kind==='notes'?'life':'notes'}/></div>;}
function Life({data,filter,setFilter,lightbox}){const list=data.photos.filter(p=>p.visible&&(filter==='全部'||p.category===filter));return <div className="page-wrap"><PageHeading eyebrow="03 / LIFE & INTERESTS" title="生活与兴趣" description={data.profile.dailyIntro}/><Interests data={data}/><div className="section-heading gallery-heading"><p className="eyebrow">IN MOMENTS</p><h2>一些生活片段</h2><p>舞台、校园与日常，把值得记住的一刻留下来。</p></div><Tabs options={['全部',...new Set(data.photos.filter(p=>p.visible).map(p=>p.category))]} value={filter} onChange={setFilter}/><div className="gallery">{list.map((p,i)=><Reveal key={p.id} className={`gallery-item ${p.id==='dinner'?'gallery-wide':''}`} delay={Math.min(i*.04,.12)}><button onClick={()=>lightbox(p.id)} className="photo-button" aria-label={`放大查看：${p.caption}`}><img src={p.src} alt={p.alt} loading="lazy" className={p.id==='cinema'?'contain-photo':''}/><span className="photo-open"><Arrow up/></span></button><div className="photo-caption"><h2>{p.caption}</h2><span>{p.category}</span></div></Reveal>)}</div>{!list.length&&<p className="empty-state">这个分类还没有照片，去其他分类看看。</p>}<section className="social-section"><h2>也在别处，记录生活。</h2><Socials data={data} full/></section><Journey next="about"/></div>;}
function About({data}){return <div className="page-wrap about-wrap"><div className="about-grid"><div><PageHeading eyebrow="04 / ABOUT POPULUS" title={<>你好，<br/>我是{data.profile.name}。</>} description={`也可以叫我 ${data.profile.englishName}。`}/><div className="about-body">{data.profile.about.split('\n\n').map((p,i)=><p key={i}>{p}</p>)}</div></div><Reveal className="about-photo"><img src={data.photos.find(x=>x.id==='campus')?.src||'/Populus-site/images/campus.jpg'} alt="校园里的胡杨赫俊"/><span>23 级 / 厚含书院 / 统计学</span></Reveal></div><section className="about-facts" aria-label="个人背景"><div><p className="eyebrow">教育背景 · 2023–2027</p><h2>统计学本科</h2><p>香港中文大学（深圳）<br/>数据科学学院 · 厚含书院</p></div><div><p className="eyebrow">实践方向</p><h2>AI 产品与前端</h2><p>需求与交互 · Web 实现<br/>数据清洗 · 特征工程</p></div><div><p className="eyebrow">校园里的角色</p><h2>组织、陪伴与表达</h2><p>羽毛球队副队长<br/>厚含主持人团队成员</p></div></section><section className="experience-section"><div className="section-heading"><p className="eyebrow">ALONG THE WAY</p><h2>几段塑造我的经历</h2></div><ol className="experience-list">{[['产品实践','海目星 · 助理 AI 产品经理','参与企业 AI 工作台的需求、产品规划、前端实现和体验验收。','/work/ai-workspace'],['市场与内容','新通教育 · 市场运营实习','参与活动与社交媒体内容运营，获评优秀“星火实习生”。','/work/content-operations'],['校园协作','活动组织与朋辈支持','参与书院外联、体育活动和新生辅导；获厚德服务奖及优秀学生助理等认可。','/work/peer-support']].map(([tag,title,desc,to])=><li key={title}><span>{tag}</span><div><h3>{title}</h3><p>{desc}</p></div><Link to={to} className="icon-button" aria-label={`了解${title}`}><Arrow up/></Link></li>)}</ol></section><section className="now-section"><p className="eyebrow">NOW / 最近在做</p><h2>保持探索，也慢慢生长。</h2><p>{data.profile.now}</p></section><ContactSection data={data}/><section className="social-section"><h2>也在别处，记录生活。</h2><Socials data={data} full/></section><Journey next="work"/></div>;}
function NotFound(){return <div className="not-found"><p className="eyebrow">404 / 还未抵达的地方</p><h1>这一页，暂时不在这里。</h1><p>也许换个方向，就会遇见新的内容。</p><Link to="/" className="button primary">回到首页<Arrow/></Link></div>;}
function SearchContent({data,query,setQuery,onNavigate,inputRef}){const q=query.trim().toLocaleLowerCase();const items=[...data.work.map(w=>({...w,url:`/work/${w.id}`,kind:'项目与实践'})),...data.notes.map(n=>({...n,url:`/notes/${n.id}`,kind:'学习笔记'})),...data.photos.filter(p=>p.visible).map(p=>({title:p.caption,summary:p.category,url:'/life',kind:'生活片段'}))];const list=q?items.filter(x=>(x.title+x.summary+(x.category||'')+(x.body||'')).toLocaleLowerCase().includes(q)):[];return <><div className="search-field"><MagnifyingGlass size={25} weight="light"/><input ref={inputRef} type="search" aria-label="输入搜索内容" placeholder="搜索项目、笔记或生活片段…" value={query} onChange={e=>setQuery(e.target.value)} autoFocus/>{query&&<button className="icon-button" onClick={()=>{setQuery('');inputRef.current?.focus();}} aria-label="清空搜索"><X size={18}/></button>}</div><div className="search-results" aria-live="polite">{!q?<div className="search-empty"><p>从一个好奇的问题开始。</p><div>{['AI','设计','校园'].map(q=><button className="search-suggestion" key={q} onClick={()=>setQuery(q)}>{q}<Arrow/></button>)}</div></div>:list.length?<><p className="result-count">找到 {list.length} 条内容</p>{list.map((x,i)=><Link to={x.url} key={x.url+i} className="search-result" onClick={onNavigate}><span className="eyebrow">{x.kind}</span><div><strong>{x.title}</strong><p>{x.summary}</p></div><Arrow/></Link>)}</>:<div className="search-empty"><h3>还没有找到相关内容</h3><p>试试更简短的关键词，或从知识页按主题浏览。</p><Link className="text-link" to="/notes" onClick={onNavigate}>浏览学习笔记<Arrow/></Link></div>}</div></>;}
export function App(){
  const [locationKey,setLocation]=useState(readRoute()+location.search);const path=locationKey.split('?')[0];
  const [data,setData]=useState(seed),[draftPreview,setDraftPreview]=useState(null),[ready,setReady]=useState(false);
  const [search,setSearch]=useState(false),[query,setQuery]=useState(''),[photo,setPhoto]=useState(null),[editor,setEditor]=useState(false),[editorTab,setEditorTab]=useState('profile'),[editing,setEditing]=useState(false),[toast,setToast]=useState('');
  const [owner,setOwner]=useState(false),[login,setLogin]=useState(false);
  const searchRef=useRef();const mainRef=useRef();const visibleData=draftPreview||data;
  const go=to=>{if(to===readRoute()+location.search)return;history.pushState(null,'',SITE_BASE+to);setLocation(to);window.scrollTo({top:0,behavior:'instant'});requestAnimationFrame(()=>mainRef.current?.focus({preventScroll:true}));};
  const notify=message=>setToast(message);const edit=async(tab='profile')=>{setEditorTab(tab);try{const session=await ownerRequest('/api/owner/session');setOwner(session.authenticated);if(session.authenticated){setEditing(true);setEditor(true);}else setLogin(true);}catch(e){notify(e.message);}};
  const exitEditing=()=>{setEditor(false);setEditing(false);setDraftPreview(null);if(path==='/admin'){history.replaceState(null,'','/');setLocation('/');}requestAnimationFrame(()=>mainRef.current?.focus({preventScroll:true}));};
  const logout=async()=>{try{await ownerRequest('/api/owner/logout',{});setOwner(false);setLogin(false);exitEditing();notify('已退出登录。');}catch(e){notify(e.message);throw e;}};
  useEffect(()=>{let alive=true;if(OWNER_ENABLED){ownerRequest('/api/site').then(value=>{if(alive&&value?.profile)setData(value);}).catch(()=>notify('内容服务暂不可用，正在显示初始内容。')).finally(()=>alive&&setReady(true));ownerRequest('/api/owner/session').then(s=>{if(alive)setOwner(s.authenticated);}).catch(()=>{});}else setReady(true);return()=>{alive=false;};},[]);
  useEffect(()=>{const pop=()=>setLocation(readRoute()+location.search);window.addEventListener('popstate',pop);const keys=e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();setSearch(v=>!v);}};window.addEventListener('popstate',pop);window.addEventListener('keydown',keys);return()=>{window.removeEventListener('popstate',pop);window.removeEventListener('keydown',keys);};},[]);
  useEffect(()=>{if(!toast)return;const timeout=setTimeout(()=>setToast(''),4500);return()=>clearTimeout(timeout);},[toast]);
  useEffect(()=>{const name=nav.find(([p])=>p===path)?.[1]||[...data.work,...data.notes].find(x=>path.endsWith('/'+x.id))?.title||'Populus';document.title=`${name} · ${data.profile.englishName} ${data.profile.name}`;},[path,data]);
  useEffect(()=>{if(path==='/admin'&&OWNER_ENABLED){edit();}},[path]);
  const filter=new URLSearchParams(locationKey.split('?')[1]).get('category')||'全部';const setFilter=category=>go(`${path}${category==='全部'?'':'?category='+encodeURIComponent(category)}`);
  const photos=visibleData.photos.filter(p=>p.visible),currentPhoto=photos.find(p=>p.id===photo),photoIndex=photos.findIndex(p=>p.id===photo);
  const cycle=offset=>setPhoto(photos[(photoIndex+offset+photos.length)%photos.length]?.id);
  let page;if(path==='/'||(path==='/admin'&&OWNER_ENABLED))page=<Home data={visibleData} editing={owner&&editing&&!draftPreview} edit={edit}/>;
  else if(path==='/work')page=<Work data={visibleData} filter={filter} setFilter={setFilter}/>;
  else if(path.startsWith('/work/'))page=<Article data={visibleData} entry={visibleData.work.find(w=>w.id===path.split('/')[2])} kind="work"/>;
  else if(path==='/notes')page=<Notes data={visibleData} filter={filter} setFilter={setFilter}/>;
  else if(path.startsWith('/notes/'))page=<Article data={visibleData} entry={visibleData.notes.find(w=>w.id===path.split('/')[2])} kind="notes"/>;
  else if(path==='/life')page=<Life data={visibleData} filter={filter} setFilter={setFilter} lightbox={setPhoto}/>;
  else if(path==='/about')page=<About data={visibleData}/>;
  else if(path==='/search')page=<div className="page-wrap"><PageHeading eyebrow="SEARCH" title="从好奇，找到答案。"/><SearchContent data={visibleData} query={query} setQuery={setQuery} inputRef={searchRef}/></div>;
  else page=<NotFound/>;
  return <Router.Provider value={{go}}><a href="#main" className="skip-link">跳转到主要内容</a><Header path={path} data={visibleData} search={()=>setSearch(true)}/>{draftPreview&&<div className="preview-banner"><span>草稿预览 · 尚未应用到站点</span><button onClick={()=>{setDraftPreview(null);edit();}}>返回编辑</button><button onClick={exitEditing}>退出编辑</button></div>}<main id="main" ref={mainRef} tabIndex={-1} key={path}>{page}</main><Footer data={visibleData} edit={()=>edit()} owner={owner} logout={()=>logout().catch(()=>{})}/>{OwnerLogin&&login&&<Suspense fallback={null}><OwnerLogin onClose={()=>{setLogin(false);if(!editor)exitEditing();}} onSuccess={()=>{setLogin(false);setOwner(true);setEditing(true);setEditor(true);}}/></Suspense>}<Modal open={search} onOpenChange={setSearch} title="搜索" className="search-dialog"><SearchContent data={visibleData} query={query} setQuery={setQuery} inputRef={searchRef} onNavigate={()=>setSearch(false)}/><div className="search-hint">项目、思考与生活 <span>Esc 关闭</span></div></Modal><Modal open={!!currentPhoto} onOpenChange={open=>!open&&setPhoto(null)} title={currentPhoto?.caption||'生活照片'} className="lightbox"><div className="lightbox-content" onKeyDown={e=>{if(e.key==='ArrowRight'){e.preventDefault();cycle(1);}if(e.key==='ArrowLeft'){e.preventDefault();cycle(-1);}}}>{currentPhoto&&<img src={currentPhoto.src} alt={currentPhoto.alt}/>}<div className="lightbox-controls"><button className="icon-button" aria-label="上一张照片" onClick={()=>cycle(-1)}><CaretLeft size={25}/></button><span>{photoIndex+1} / {photos.length}</span><button className="icon-button" aria-label="下一张照片" onClick={()=>cycle(1)}><CaretRight size={25}/></button></div></div></Modal>{Editor&&owner&&editor&&ready&&<Suspense fallback={<div className="toast" role="status">正在打开编辑工作台…</div>}><Editor data={data} initialTab={editorTab} onClose={exitEditing} onLogout={logout} onReauthenticate={()=>setLogin(true)} onPasswordChanged={()=>{setOwner(false);exitEditing();setLogin(true);notify("密码已更新，请重新登录。");}} onPreview={value=>{setDraftPreview(value);setEditor(false);if(path==='/admin')go('/');}} onApply={value=>{setData(value);setDraftPreview(null);}} notify={notify}/></Suspense>}{owner&&editing&&!editor&&!draftPreview&&<><button className="edit-control edit-floating" aria-label="编辑内容" onClick={()=>edit()}><PencilSimple size={17} aria-hidden="true"/><span className="edit-tooltip" aria-hidden="true">编辑内容</span></button><button className="edit-control edit-exit" aria-label="退出编辑" onClick={exitEditing}><SignOut size={17} aria-hidden="true"/><span className="edit-tooltip" aria-hidden="true">退出编辑</span></button></>}{toast&&<div className="toast" role="status"><Check size={18}/>{toast}<button className="icon-button" aria-label="关闭提示" onClick={()=>setToast('')}><X size={16}/></button></div>}</Router.Provider>;
}
