import React,{useEffect,useState,useRef} from 'react';
import {PencilSimple,ImageSquare,FileText,UploadSimple,ArrowUp,ArrowDown,Eye,EyeSlash,ClockCounterClockwise,FloppyDisk,ArrowRight,Check} from '@phosphor-icons/react';
import {Modal} from './App';
import {readLocal,writeLocal,applyLocal,imageData,ownerRequest,readLegacyDraft} from './storage';
const fields=[['name','中文姓名'],['englishName','英文名'],['headline','首页主标题'],['accent','首页强调句'],['intro','首页介绍'],['about','关于我的介绍'],['now','最近在做'],['dailyIntro','生活页自我介绍'],['interests','兴趣标签（每行一个）'],['wechat','微信号'],['email','联系邮箱'],['phone','联系电话']];
function Field({label,value,onChange,long=false,...props}){return <label className="editor-field"><span>{label}</span>{long?<textarea value={value||''} onChange={e=>onChange(e.target.value)} rows={label.includes('正文')?16:4} {...props}/>:<input value={value||''} onChange={e=>onChange(e.target.value)} {...props}/>}</label>;}
export default function Editor({data,initialTab,onClose,onPreview,onApply,notify,onLogout,onReauthenticate,onPasswordChanged}){
 const [draft,setDraft]=useState(()=>structuredClone(data)),[tab,setTab]=useState(initialTab),[loaded,setLoaded]=useState(false),[busy,setBusy]=useState(false),[dirty,setDirty]=useState(false),[status,setStatus]=useState('读取站主草稿…'),[error,setError]=useState(''),[entryKey,setEntryKey]=useState('work:0'),[previous,setPrevious]=useState(null),[drag,setDrag]=useState(false);
 const [currentPassword,setCurrentPassword]=useState(''),[newPassword,setNewPassword]=useState('');
 const fileRef=useRef();const replaceRef=useRef(null);const baseStamp=useRef(null);
 useEffect(()=>{let alive=true;Promise.all([readLocal('draft'),readLocal('previous')]).then(([saved,prev])=>{if(!alive)return;if(saved?.profile){setDraft(saved);baseStamp.current=saved.savedAt||null;}setPrevious(prev);setStatus(saved?'已载入草稿':'可以开始编辑');}).catch(()=>{if(alive)setError('无法读取草稿，请重新验证登录后重试。');}).finally(()=>alive&&setLoaded(true));return()=>{alive=false;};},[]);
 const mutate=fn=>{setDraft(old=>fn(structuredClone(old)));setDirty(true);setStatus('有尚未保存的修改');setError('');};
 const profile=(key,value)=>mutate(d=>{d.profile[key]=value;return d;});
 const validate=()=>{if(!draft.profile.name.trim()||!draft.profile.englishName.trim())throw new Error('请填写中文姓名和英文名。');for(const s of draft.socials){try{const u=new URL(s.url);if(u.protocol!=='https:')throw Error();}catch{throw new Error(`${s.label}链接需要是完整的 HTTPS 网址。`);}}for(const p of draft.photos){if(p.visible&&(!p.caption.trim()||!p.alt.trim()))throw new Error('展示的照片需要填写说明和图片描述。');}};
 async function save(){validate();const current=await readLocal('draft');if((current?.savedAt||null)!==baseStamp.current)throw new Error('草稿已在另一个窗口修改。请先关闭并重新打开编辑器，再合并修改。');const next=await writeLocal('draft',draft,baseStamp.current);baseStamp.current=next.savedAt;setDraft(next);setDirty(false);setStatus('草稿已保存到服务端');return next;}
 const action=async(kind)=>{if(busy||!loaded)return;setBusy(true);setError('');try{const value=await save();if(kind==='apply'){const applied=await applyLocal(value);onApply(applied);setPrevious(await readLocal('previous'));setStatus('已应用到本站');notify('内容已应用到本站。');}else if(kind==='preview'){onPreview(value);}else notify('草稿已保存。');}catch(e){setError(e.message||'保存失败，修改仍保留在编辑器中，请重试。');}finally{setBusy(false);}};
 const close=async(done=onClose)=>{if(busy)return;if(dirty){setBusy(true);try{await save();await done();}catch(e){setError(e.message);setBusy(false);}}else {try{await done();}catch(e){setError(e.message);}}};
 async function changePassword(e){e.preventDefault();if(busy||!loaded)return;setBusy(true);setError('');try{if(dirty)await save();await ownerRequest('/api/owner/password',{currentPassword,password:newPassword});setCurrentPassword('');setNewPassword('');onPasswordChanged();}catch(e){setError(e.message);}finally{setBusy(false);}}
 async function importLegacy(){if(busy||!loaded)return;setBusy(true);setError('');try{const old=await readLegacyDraft();if(!old?.profile){setStatus('这个浏览器没有旧版草稿。');return;}if(dirty)await save();setDraft(old);setDirty(true);setStatus('旧草稿已载入，检查后保存；不会自动应用到本站。');}catch(e){setError(e.message);}finally{setBusy(false);}}
 async function upload(files){if(!files?.length)return;if(files.length>10){setError('每次最多添加 10 张照片。');return;}setBusy(true);setError('');const added=[];let failure=[];for(const file of Array.from(files)){setStatus(`正在处理 ${file.name}`);try{const src=await imageData(file);if(replaceRef.current==='hero'){profile('hero',src);break;}if(replaceRef.current){const id=replaceRef.current;mutate(d=>{d.photos=d.photos.map(p=>p.id===id?{...p,src}:p);return d;});break;}added.push({id:crypto.randomUUID(),src,caption:file.name.replace(/\.[^.]+$/,''),alt:'',category:'日常',visible:false});}catch(e){failure.push(`${file.name}：${e.message}`);}}if(added.length)mutate(d=>{d.photos.push(...added);return d;});replaceRef.current=null;setBusy(false);setStatus(added.length?'已添加。填写图片描述并开启展示后保存。':'图片已处理，请保存草稿。');if(failure.length)setError(failure.join('\n'));}
 const pick=(id=null)=>{replaceRef.current=id;fileRef.current.value='';fileRef.current.click();};
 const photoField=(id,key,value)=>mutate(d=>{d.photos=d.photos.map(p=>p.id===id?{...p,[key]:value}:p);return d;});
 const move=(index,offset)=>mutate(d=>{const other=index+offset;if(other<0||other>=d.photos.length)return d;[d.photos[index],d.photos[other]]=[d.photos[other],d.photos[index]];return d;});
 const [kind,entryIndex]=entryKey.split(':');const entry=draft[kind][Number(entryIndex)];
 return <Modal open onOpenChange={open=>!open&&close()} title="内容工作台" closeLabel="退出编辑" description="在页面里，慢慢整理属于你的内容。" className="editor-dialog"><div className="local-notice">站主已登录 · 保存草稿仅自己可见，应用后更新本站。</div><div className="editor-tabs">{[['profile','个人信息',PencilSimple],['photos','图片管理',ImageSquare],['content','实践与笔记',FileText]].map(([id,label,Icon])=><button key={id} onClick={()=>setTab(id)} aria-pressed={tab===id}><Icon size={18}/>{label}</button>)}</div><div className="editor-scroll" aria-busy={busy||!loaded}><fieldset className="editor-fields" disabled={busy||!loaded}><input ref={fileRef} className="sr-only" type="file" accept="image/jpeg,image/png,image/webp" multiple onChange={e=>upload(e.target.files)} aria-label="选择上传图片"/>
 {tab==='profile'&&<><div className="editor-image-preview"><img src={draft.profile.hero} alt="当前首页背景"/><button className="button secondary" onClick={()=>pick('hero')} disabled={busy}><UploadSimple/>替换首页图片</button></div>{fields.map(([key,label])=><Field key={key} label={label} value={draft.profile[key]} long={['intro','about','now','dailyIntro','interests'].includes(key)} maxLength={['name','englishName'].includes(key)?32:3000} onChange={value=>profile(key,value)}/>)}<h3 className="editor-subheading">在别处找到我</h3>{draft.socials.map((s,index)=><Field key={s.label} label={`${s.label}链接`} value={s.url} onChange={url=>mutate(d=>{d.socials[index].url=url;return d;})}/>)}</>}
 {tab==='photos'&&<><button className={`upload-area ${drag?'is-dragging':''}`} disabled={busy} onClick={()=>pick()} onDragOver={e=>{e.preventDefault();setDrag(true);}} onDragLeave={()=>setDrag(false)} onDrop={e=>{e.preventDefault();setDrag(false);replaceRef.current=null;if(!busy)upload(e.dataTransfer.files);}}><UploadSimple size={30} weight="light"/><strong>点击选图，或将照片拖到这里</strong><span>JPG、PNG、WebP · 单张最多 15 MB</span></button><p className="editor-help">新照片默认隐藏。填写说明后开启展示，草稿预览中就能看到。</p>{draft.photos.map((p,i)=><div className="edit-photo" key={p.id}><div className="edit-photo-top"><img src={p.src} alt={p.alt||'新增照片预览'}/><div><button className="text-link" onClick={()=>pick(p.id)} disabled={busy}>替换图片<UploadSimple/></button><div className="photo-order"><button className="icon-button" aria-label={`上移：${p.caption}`} onClick={()=>move(i,-1)} disabled={i===0}><ArrowUp/></button><button className="icon-button" aria-label={`下移：${p.caption}`} onClick={()=>move(i,1)} disabled={i===draft.photos.length-1}><ArrowDown/></button><button className="visibility-button" aria-pressed={p.visible} onClick={()=>photoField(p.id,'visible',!p.visible)}>{p.visible?<Eye/>:<EyeSlash/>}{p.visible?'展示中':'已隐藏'}</button></div></div></div><Field label="照片说明" value={p.caption} onChange={v=>photoField(p.id,'caption',v)}/><Field label="图片描述（用于无障碍阅读）" value={p.alt} onChange={v=>photoField(p.id,'alt',v)}/><Field label="分类" value={p.category} onChange={v=>photoField(p.id,'category',v)}/></div>)}</>}
 {tab==='content'&&<><label className="editor-field"><span>选择要修改的内容</span><select value={entryKey} onChange={e=>setEntryKey(e.target.value)}>{['work','notes'].flatMap(k=>draft[k].map((e,i)=><option value={`${k}:${i}`} key={`${k}:${i}`}>{k==='work'?'实践':'笔记'} · {e.title}</option>))}</select></label>{[['title','标题'],['summary','摘要'],['body','正文（Markdown）']].map(([key,label])=><Field key={entryKey+key} label={label} long={key!=='title'} value={entry[key]} onChange={value=>mutate(d=>{d[kind][Number(entryIndex)][key]=value;return d;})}/>)}<p className="editor-help">支持 Markdown 标题、段落、列表、引用和链接。完整效果可在草稿预览中查看。</p></>}
 <div className="editor-history"><button className="text-link" disabled={busy||!loaded} onClick={importLegacy}>导入旧版浏览器草稿</button><details className="owner-password"><summary>修改站主密码</summary><form onSubmit={changePassword}><Field label="当前密码" type="password" autoComplete="current-password" value={currentPassword} onChange={setCurrentPassword}/><Field label="新密码（至少 12 位）" type="password" autoComplete="new-password" value={newPassword} onChange={setNewPassword}/><button className="button secondary" disabled={busy||!loaded||newPassword.length<12||!currentPassword} type="submit">更新密码并退出登录</button></form></details><button className="text-link" disabled={busy||!previous} onClick={()=>{if(previous){setDraft(structuredClone(previous));setDirty(true);setStatus('已载入上一版，预览后再应用。');}}}><ClockCounterClockwise/>载入上一次应用的内容</button></div></fieldset></div>{error&&<div className="editor-error"><p role="alert">{error}</p>{dirty&&<button className="text-link" onClick={onClose} disabled={busy}>放弃本次未保存修改并退出编辑</button>}</div>}<div className="editor-bottom"><div className="editor-session"><button onClick={onReauthenticate} disabled={busy}>重新验证登录</button><button onClick={()=>close(onLogout)} disabled={busy}>退出登录</button></div><div className="save-status" role="status">{!dirty&&!busy?<Check size={14}/>:<span/>}{status}</div><div className="editor-actions"><button className="button secondary" disabled={busy||!loaded} onClick={()=>action('save')}><FloppyDisk/>保存草稿</button><button className="button secondary" disabled={busy||!loaded} onClick={()=>action('preview')}><Eye/>预览</button><button className="button primary" disabled={busy||!loaded} onClick={()=>action('apply')}>应用到本站<ArrowRight/></button></div></div></Modal>;
}
